---
###############################################################################
################################# INSTALL #####################################
###############################################################################


# - debug: var=preexisting


- block:
  - name: add homebride system group
    group:
        name: "{{ hb_group }}"
        state: present
        system: true
  - name: add homebridge service account
    user:
        name: "{{ hb_user }}"
        comment: "Homebridge Service Account"
        group: "{{ hb_group }}"
        home: "{{ hb_prefix }}"
        shell: /usr/sbin/nologin
        password_lock: true
  become: yes
  become_user: root
  tags: vault_add_user
