---
###############################################################################
################################# INSTALL #####################################
###############################################################################

- stat:
    path: "{{ hb_prefix }}"
  register: installed_ok
  tags:
    - hb_systemd

- block:
  - name: create the tld  paths
    file:
      path: "{{ hb_prefix }}/"
      state: directory
      mode: 0755
      owner: "{{hb_user}}"
      group: "{{hb_group}}"
  - name: create the conf paths
    file:
      path: "{{ hb_conf_dir }}"
      state: directory
      mode: 0755
      owner: "{{hb_user}}"
      group: "{{hb_group}}"
  when: installed_ok.stat.exists == true


###############################################################################
################################ Initial Pull ####################################
###############################################################################


- name: Pull latest hb image
  shell: "{{podman_path}} pull oznu/homebridge:latest"
  args:
    executable: /bin/bash
  register: pull_ok
  become_user: "{{hb_user}}"
  become: true
- debug:
   msg: "{{pull_ok}}"


#--name=hb  --env-file=envfile -v ./etc-hb/:/etc/hb/:z -v ./etc-dnsmasq.d/:/etc/dnsmasq.d/:z --network=host hb/hb:latest

###############################################################################
################################ CONFIGURE ####################################
###############################################################################

- block:

  - name: Add envfile for pihhole
    template:
      src: hb.envfile.j2
      dest: "{{hb_env_file}}"
      mode: 0600
      owner: "{{hb_user}}"
      group: "{{hb_group}}"
    notify: restart hb

  - name: Add default ad lists for gravity DB
    template:
      src: config.json.j2
      dest: "{{hb_conf_dir}}/config.json"
      mode: 0600
      owner: "{{hb_user}}"
      group: "{{hb_group}}"

  - name: Add default ad lists for gravity DB
    template:
      src: auth.json.j2
      dest: "{{hb_conf_dir}}/auth.json"
      mode: 0600
      owner: "{{hb_user}}"
      group: "{{hb_group}}"

  - name: Add default plugin lists
    template:
      src: package.json.j2
      dest: "{{hb_conf_dir}}/package.json"
      mode: 0600
      owner: "{{hb_user}}"
      group: "{{hb_group}}"

  - name: First run of image (no idea if I can )
    shell: "{{podman_path}} run -d --replace=true --net=host --name=homebridge --env-file={{ hb_env_file }} -v {{ hb_conf_dir}}:/homebridge oznu/homebridge"
    args:
      executable: /bin/bash
    register: pull_ok
    become_user: "{{ hb_user }}"

  - name: configure hb for systemd
    template:
      src: hb.service.j2
      dest: "{{ systemd_dir }}/hb.service"
      mode: 0644
    notify: reload systemd

  - name: enable hb
    service:
      name: hb
      enabled: yes
      state: started

  become: yes
  become_user: "root"
  tags: hb_systemd
